# Dependabot configuration for automated dependency updates
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for Bundler (Ruby dependencies)
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "godaddy/oss-defenders"
    labels:
      - "dependencies"
      - "ruby"
    groups:
      development-dependencies:
        patterns:
          - "rubocop*"
          - "rspec*"
          - "cucumber*"
          - "simplecov*"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "godaddy/oss-defenders"
    labels:
      - "dependencies"
      - "github-actions"