AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*' # Github Actions
    - 'tmp/**/*'

Layout/LineLength:
  Max: 120

# Metrics cops with reasonable limits
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'spec/**/*'

# Style cops that were disabled but should be enabled
Style/WordArray:
  MinSize: 3
  EnforcedStyle: brackets

Style/SymbolArray:
  MinSize: 3
  EnforcedStyle: brackets

Style/MultilineBlockChain:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - let
    - let!
    - subject
    - before
    - after
  Exclude:
    - 'asherah.gemspec'
    - 'ext/asherah/native_file.rb'

Style/GuardClause:
  MinBodyLength: 3
  Exclude:
    - 'ext/asherah/native_file.rb'

# Naming cop adjustment
Naming/AccessorMethodName:
  Exclude:
    - 'lib/asherah.rb' # set_env is intentionally named

# Documentation cops
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'

Style/DocumentationMethod:
  Enabled: false # YARD comments are optional

# Additional cops for code quality
Lint/UnusedMethodArgument:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true