name: Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ruby-${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ]
        ruby: [ 2.5, 2.6, 2.7, 3.0, 3.1 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: Download binaries
        run: |
          bin/download-asherah.sh

      - name: Run specs
        run: |
          COVERAGE=true bundle exec rspec spec

      - name: Run rubocop
        run: |
          bundle exec rubocop
