name: Integration

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

env:
  MYSQL_HOSTNAME: mysql
  MYSQL_DATABASE: testdb
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: Password123

jobs:
  integration:
    runs-on: ubuntu-latest
    name: integration
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler: default
          bundler-cache: true

      - name: Download binary for current platform
        run: |
          bundle exec rake native:current:download

      - name: Test Cross-Language
        env:
          TEST_DB_NAME: ${{ env.MYSQL_DATABASE }}
          TEST_DB_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          TEST_DB_HOSTNAME: ${{ env.MYSQL_HOSTNAME }}
          TEST_DB_USER: ${{ env.MYSQL_USERNAME }}
          TEST_DB_PORT: ${{ job.services.mysql.ports[3306] }}
          ASHERAH_SERVICE_NAME: service
          ASHERAH_PRODUCT_NAME: product
          ASHERAH_KMS_MODE: static
        run: |
          bundle exec cucumber features/encrypt.feature
          bundle exec cucumber features/decrypt.feature
