name: Publish

# To release a new version of native gems, create a tag and Github release.

on:
  release:
    types: [published] # Trigger when release is created

jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    name: publish
    steps:
      - uses: actions/checkout@v5

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler: default
          bundler-cache: true

      - name: Build gems
        run: |
          bundle exec rake build
          bundle exec rake native:build

      - name: Push gems
        run: |
          for file in pkg/*.gem; do gem push $file || echo "already published"; done
